package com.chen.xinyueweather.dao.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.chen.xinyueweather.dao.bean.CityManage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CITY_MANAGE".
*/
public class CityManageDao extends AbstractDao<CityManage, Long> {

    public static final String TABLENAME = "CITY_MANAGE";

    /**
     * Properties of entity CityManage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property TabId = new Property(0, Long.class, "tabId", true, "_id");
        public final static Property AreaName = new Property(1, String.class, "areaName", false, "AREA_NAME");
        public final static Property Weather = new Property(2, String.class, "weather", false, "WEATHER");
        public final static Property Temperature = new Property(3, String.class, "temperature", false, "TEMPERATURE");
        public final static Property WeatherId = new Property(4, String.class, "weatherId", false, "WEATHER_ID");
    }


    public CityManageDao(DaoConfig config) {
        super(config);
    }
    
    public CityManageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CITY_MANAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: tabId
                "\"AREA_NAME\" TEXT," + // 1: areaName
                "\"WEATHER\" TEXT," + // 2: weather
                "\"TEMPERATURE\" TEXT," + // 3: temperature
                "\"WEATHER_ID\" TEXT);"); // 4: weatherId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CITY_MANAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CityManage entity) {
        stmt.clearBindings();
 
        Long tabId = entity.getTabId();
        if (tabId != null) {
            stmt.bindLong(1, tabId);
        }
 
        String areaName = entity.getAreaName();
        if (areaName != null) {
            stmt.bindString(2, areaName);
        }
 
        String weather = entity.getWeather();
        if (weather != null) {
            stmt.bindString(3, weather);
        }
 
        String temperature = entity.getTemperature();
        if (temperature != null) {
            stmt.bindString(4, temperature);
        }
 
        String weatherId = entity.getWeatherId();
        if (weatherId != null) {
            stmt.bindString(5, weatherId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CityManage entity) {
        stmt.clearBindings();
 
        Long tabId = entity.getTabId();
        if (tabId != null) {
            stmt.bindLong(1, tabId);
        }
 
        String areaName = entity.getAreaName();
        if (areaName != null) {
            stmt.bindString(2, areaName);
        }
 
        String weather = entity.getWeather();
        if (weather != null) {
            stmt.bindString(3, weather);
        }
 
        String temperature = entity.getTemperature();
        if (temperature != null) {
            stmt.bindString(4, temperature);
        }
 
        String weatherId = entity.getWeatherId();
        if (weatherId != null) {
            stmt.bindString(5, weatherId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CityManage readEntity(Cursor cursor, int offset) {
        CityManage entity = new CityManage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // tabId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // areaName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // weather
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // temperature
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // weatherId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CityManage entity, int offset) {
        entity.setTabId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAreaName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWeather(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTemperature(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setWeatherId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CityManage entity, long rowId) {
        entity.setTabId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CityManage entity) {
        if(entity != null) {
            return entity.getTabId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CityManage entity) {
        return entity.getTabId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
