package com.chen.xinyueweather.dao.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.chen.xinyueweather.dao.bean.Index;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INDEX".
*/
public class IndexDao extends AbstractDao<Index, Long> {

    public static final String TABLENAME = "INDEX";

    /**
     * Properties of entity Index.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AreaId = new Property(1, String.class, "areaId", false, "AREA_ID");
        public final static Property Abbreviation = new Property(2, String.class, "abbreviation", false, "ABBREVIATION");
        public final static Property Alias = new Property(3, String.class, "alias", false, "ALIAS");
        public final static Property Content = new Property(4, String.class, "content", false, "CONTENT");
        public final static Property Level = new Property(5, String.class, "level", false, "LEVEL");
        public final static Property Name = new Property(6, String.class, "name", false, "NAME");
    }


    public IndexDao(DaoConfig config) {
        super(config);
    }
    
    public IndexDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INDEX\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"AREA_ID\" TEXT," + // 1: areaId
                "\"ABBREVIATION\" TEXT," + // 2: abbreviation
                "\"ALIAS\" TEXT," + // 3: alias
                "\"CONTENT\" TEXT," + // 4: content
                "\"LEVEL\" TEXT," + // 5: level
                "\"NAME\" TEXT);"); // 6: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INDEX\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Index entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String areaId = entity.getAreaId();
        if (areaId != null) {
            stmt.bindString(2, areaId);
        }
 
        String abbreviation = entity.getAbbreviation();
        if (abbreviation != null) {
            stmt.bindString(3, abbreviation);
        }
 
        String alias = entity.getAlias();
        if (alias != null) {
            stmt.bindString(4, alias);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
 
        String level = entity.getLevel();
        if (level != null) {
            stmt.bindString(6, level);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(7, name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Index entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String areaId = entity.getAreaId();
        if (areaId != null) {
            stmt.bindString(2, areaId);
        }
 
        String abbreviation = entity.getAbbreviation();
        if (abbreviation != null) {
            stmt.bindString(3, abbreviation);
        }
 
        String alias = entity.getAlias();
        if (alias != null) {
            stmt.bindString(4, alias);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
 
        String level = entity.getLevel();
        if (level != null) {
            stmt.bindString(6, level);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(7, name);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Index readEntity(Cursor cursor, int offset) {
        Index entity = new Index( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // areaId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // abbreviation
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // alias
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // content
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // level
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Index entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAreaId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAbbreviation(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAlias(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setContent(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLevel(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Index entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Index entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Index entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
