package com.chen.xinyueweather.dao.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.chen.xinyueweather.dao.bean.WeathersBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEATHERS_BEAN".
*/
public class WeathersBeanDao extends AbstractDao<WeathersBean, Void> {

    public static final String TABLENAME = "WEATHERS_BEAN";

    /**
     * Properties of entity WeathersBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Date = new Property(0, String.class, "date", false, "DATE");
        public final static Property Img = new Property(1, String.class, "img", false, "IMG");
        public final static Property Sun_down_time = new Property(2, String.class, "sun_down_time", false, "SUN_DOWN_TIME");
        public final static Property Sun_rise_time = new Property(3, String.class, "sun_rise_time", false, "SUN_RISE_TIME");
        public final static Property Temp_day_c = new Property(4, String.class, "temp_day_c", false, "TEMP_DAY_C");
        public final static Property Temp_day_f = new Property(5, String.class, "temp_day_f", false, "TEMP_DAY_F");
        public final static Property Temp_night_c = new Property(6, String.class, "temp_night_c", false, "TEMP_NIGHT_C");
        public final static Property Temp_night_f = new Property(7, String.class, "temp_night_f", false, "TEMP_NIGHT_F");
        public final static Property Wd = new Property(8, String.class, "wd", false, "WD");
        public final static Property Weather = new Property(9, String.class, "weather", false, "WEATHER");
        public final static Property Week = new Property(10, String.class, "week", false, "WEEK");
        public final static Property Ws = new Property(11, String.class, "ws", false, "WS");
    }


    public WeathersBeanDao(DaoConfig config) {
        super(config);
    }
    
    public WeathersBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEATHERS_BEAN\" (" + //
                "\"DATE\" TEXT," + // 0: date
                "\"IMG\" TEXT," + // 1: img
                "\"SUN_DOWN_TIME\" TEXT," + // 2: sun_down_time
                "\"SUN_RISE_TIME\" TEXT," + // 3: sun_rise_time
                "\"TEMP_DAY_C\" TEXT," + // 4: temp_day_c
                "\"TEMP_DAY_F\" TEXT," + // 5: temp_day_f
                "\"TEMP_NIGHT_C\" TEXT," + // 6: temp_night_c
                "\"TEMP_NIGHT_F\" TEXT," + // 7: temp_night_f
                "\"WD\" TEXT," + // 8: wd
                "\"WEATHER\" TEXT," + // 9: weather
                "\"WEEK\" TEXT," + // 10: week
                "\"WS\" TEXT);"); // 11: ws
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEATHERS_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WeathersBean entity) {
        stmt.clearBindings();
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(1, date);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(2, img);
        }
 
        String sun_down_time = entity.getSun_down_time();
        if (sun_down_time != null) {
            stmt.bindString(3, sun_down_time);
        }
 
        String sun_rise_time = entity.getSun_rise_time();
        if (sun_rise_time != null) {
            stmt.bindString(4, sun_rise_time);
        }
 
        String temp_day_c = entity.getTemp_day_c();
        if (temp_day_c != null) {
            stmt.bindString(5, temp_day_c);
        }
 
        String temp_day_f = entity.getTemp_day_f();
        if (temp_day_f != null) {
            stmt.bindString(6, temp_day_f);
        }
 
        String temp_night_c = entity.getTemp_night_c();
        if (temp_night_c != null) {
            stmt.bindString(7, temp_night_c);
        }
 
        String temp_night_f = entity.getTemp_night_f();
        if (temp_night_f != null) {
            stmt.bindString(8, temp_night_f);
        }
 
        String wd = entity.getWd();
        if (wd != null) {
            stmt.bindString(9, wd);
        }
 
        String weather = entity.getWeather();
        if (weather != null) {
            stmt.bindString(10, weather);
        }
 
        String week = entity.getWeek();
        if (week != null) {
            stmt.bindString(11, week);
        }
 
        String ws = entity.getWs();
        if (ws != null) {
            stmt.bindString(12, ws);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WeathersBean entity) {
        stmt.clearBindings();
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(1, date);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(2, img);
        }
 
        String sun_down_time = entity.getSun_down_time();
        if (sun_down_time != null) {
            stmt.bindString(3, sun_down_time);
        }
 
        String sun_rise_time = entity.getSun_rise_time();
        if (sun_rise_time != null) {
            stmt.bindString(4, sun_rise_time);
        }
 
        String temp_day_c = entity.getTemp_day_c();
        if (temp_day_c != null) {
            stmt.bindString(5, temp_day_c);
        }
 
        String temp_day_f = entity.getTemp_day_f();
        if (temp_day_f != null) {
            stmt.bindString(6, temp_day_f);
        }
 
        String temp_night_c = entity.getTemp_night_c();
        if (temp_night_c != null) {
            stmt.bindString(7, temp_night_c);
        }
 
        String temp_night_f = entity.getTemp_night_f();
        if (temp_night_f != null) {
            stmt.bindString(8, temp_night_f);
        }
 
        String wd = entity.getWd();
        if (wd != null) {
            stmt.bindString(9, wd);
        }
 
        String weather = entity.getWeather();
        if (weather != null) {
            stmt.bindString(10, weather);
        }
 
        String week = entity.getWeek();
        if (week != null) {
            stmt.bindString(11, week);
        }
 
        String ws = entity.getWs();
        if (ws != null) {
            stmt.bindString(12, ws);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public WeathersBean readEntity(Cursor cursor, int offset) {
        WeathersBean entity = new WeathersBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // date
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // img
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sun_down_time
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // sun_rise_time
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // temp_day_c
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // temp_day_f
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // temp_night_c
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // temp_night_f
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // wd
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // weather
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // week
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // ws
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WeathersBean entity, int offset) {
        entity.setDate(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setImg(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSun_down_time(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSun_rise_time(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTemp_day_c(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTemp_day_f(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTemp_night_c(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTemp_night_f(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setWd(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setWeather(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setWeek(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setWs(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(WeathersBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(WeathersBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(WeathersBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
