package com.chen.xinyueweather.dao.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.chen.xinyueweather.dao.bean.Weather3HoursDetailsInfosBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEATHER3_HOURS_DETAILS_INFOS_BEAN".
*/
public class Weather3HoursDetailsInfosBeanDao extends AbstractDao<Weather3HoursDetailsInfosBean, Long> {

    public static final String TABLENAME = "WEATHER3_HOURS_DETAILS_INFOS_BEAN";

    /**
     * Properties of entity Weather3HoursDetailsInfosBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AreaId = new Property(1, String.class, "areaId", false, "AREA_ID");
        public final static Property EndTime = new Property(2, String.class, "endTime", false, "END_TIME");
        public final static Property HighestTemperature = new Property(3, String.class, "highestTemperature", false, "HIGHEST_TEMPERATURE");
        public final static Property Img = new Property(4, String.class, "img", false, "IMG");
        public final static Property IsRainFall = new Property(5, String.class, "isRainFall", false, "IS_RAIN_FALL");
        public final static Property LowerestTemperature = new Property(6, String.class, "lowerestTemperature", false, "LOWEREST_TEMPERATURE");
        public final static Property Precipitation = new Property(7, String.class, "precipitation", false, "PRECIPITATION");
        public final static Property StartTime = new Property(8, String.class, "startTime", false, "START_TIME");
        public final static Property Wd = new Property(9, String.class, "wd", false, "WD");
        public final static Property Weather = new Property(10, String.class, "weather", false, "WEATHER");
        public final static Property Ws = new Property(11, String.class, "ws", false, "WS");
    }


    public Weather3HoursDetailsInfosBeanDao(DaoConfig config) {
        super(config);
    }
    
    public Weather3HoursDetailsInfosBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEATHER3_HOURS_DETAILS_INFOS_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"AREA_ID\" TEXT," + // 1: areaId
                "\"END_TIME\" TEXT," + // 2: endTime
                "\"HIGHEST_TEMPERATURE\" TEXT," + // 3: highestTemperature
                "\"IMG\" TEXT," + // 4: img
                "\"IS_RAIN_FALL\" TEXT," + // 5: isRainFall
                "\"LOWEREST_TEMPERATURE\" TEXT," + // 6: lowerestTemperature
                "\"PRECIPITATION\" TEXT," + // 7: precipitation
                "\"START_TIME\" TEXT," + // 8: startTime
                "\"WD\" TEXT," + // 9: wd
                "\"WEATHER\" TEXT," + // 10: weather
                "\"WS\" TEXT);"); // 11: ws
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEATHER3_HOURS_DETAILS_INFOS_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Weather3HoursDetailsInfosBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String areaId = entity.getAreaId();
        if (areaId != null) {
            stmt.bindString(2, areaId);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(3, endTime);
        }
 
        String highestTemperature = entity.getHighestTemperature();
        if (highestTemperature != null) {
            stmt.bindString(4, highestTemperature);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(5, img);
        }
 
        String isRainFall = entity.getIsRainFall();
        if (isRainFall != null) {
            stmt.bindString(6, isRainFall);
        }
 
        String lowerestTemperature = entity.getLowerestTemperature();
        if (lowerestTemperature != null) {
            stmt.bindString(7, lowerestTemperature);
        }
 
        String precipitation = entity.getPrecipitation();
        if (precipitation != null) {
            stmt.bindString(8, precipitation);
        }
 
        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(9, startTime);
        }
 
        String wd = entity.getWd();
        if (wd != null) {
            stmt.bindString(10, wd);
        }
 
        String weather = entity.getWeather();
        if (weather != null) {
            stmt.bindString(11, weather);
        }
 
        String ws = entity.getWs();
        if (ws != null) {
            stmt.bindString(12, ws);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Weather3HoursDetailsInfosBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String areaId = entity.getAreaId();
        if (areaId != null) {
            stmt.bindString(2, areaId);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(3, endTime);
        }
 
        String highestTemperature = entity.getHighestTemperature();
        if (highestTemperature != null) {
            stmt.bindString(4, highestTemperature);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(5, img);
        }
 
        String isRainFall = entity.getIsRainFall();
        if (isRainFall != null) {
            stmt.bindString(6, isRainFall);
        }
 
        String lowerestTemperature = entity.getLowerestTemperature();
        if (lowerestTemperature != null) {
            stmt.bindString(7, lowerestTemperature);
        }
 
        String precipitation = entity.getPrecipitation();
        if (precipitation != null) {
            stmt.bindString(8, precipitation);
        }
 
        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(9, startTime);
        }
 
        String wd = entity.getWd();
        if (wd != null) {
            stmt.bindString(10, wd);
        }
 
        String weather = entity.getWeather();
        if (weather != null) {
            stmt.bindString(11, weather);
        }
 
        String ws = entity.getWs();
        if (ws != null) {
            stmt.bindString(12, ws);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Weather3HoursDetailsInfosBean readEntity(Cursor cursor, int offset) {
        Weather3HoursDetailsInfosBean entity = new Weather3HoursDetailsInfosBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // areaId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // endTime
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // highestTemperature
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // img
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // isRainFall
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // lowerestTemperature
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // precipitation
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // startTime
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // wd
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // weather
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // ws
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Weather3HoursDetailsInfosBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAreaId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEndTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHighestTemperature(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setImg(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIsRainFall(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLowerestTemperature(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPrecipitation(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setStartTime(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setWd(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setWeather(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setWs(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Weather3HoursDetailsInfosBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Weather3HoursDetailsInfosBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Weather3HoursDetailsInfosBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
